services:
  db:
    image: postgres:16-alpine
    container_name: cs2_smokes_hub_db
    restart: always
    environment:
      POSTGRES_USER: cs2
      POSTGRES_PASSWORD: cs2
      POSTGRES_DB: cs2_smokes_hub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
